### ISSUE TITLE
Überstundenausgleich werden nicht in der Einzelübersicht berücksichtigt

### ISSUE THREAD

**Issue by TimZielasko** [HBTGmbH/salat#10]
Wenn man in einem Monat Überstundenausgleich genommen/gebucht hat, werden diese nicht auf der Einzelübersichtsseite bei den gebuchten IST Stunden berücksichtigt. 
Dies führt regelmäßig zur Verwirrung, ob man jeden Arbeitstag auch ordnungsgemäß gebucht hat.
Bitte den Überstundenausgleich mit berücksichtigen, in den IST Stunden auf der Einzelübersichtsseite

**Comment by KlausRicharz** [comment]
Man könnte für jeden Tag, in dem Überstundenausgleich gebucht ist, die (nicht gearbeiteten) Stunden berechnen und getrennt aufführen und entsprechend die Ist-Zeit erweitern. (z.B. eine Kennzahl Ist + Überstundenausgleich - Sollzeit). Das hilft dann ggf. bei der Monatsplanung, wenn man vor hat, Überstunden abzubauen. Geht das in die richtige Richtung?
