### ISSUE TITLE
Urlaub tageweise buchen 

### ISSUE THREAD

**Issue by anoHBT** [HBTGmbH/salat#11]
Ich möchte als Benutzer tageweise Urlaub buchen. Der Salat rechnet dann die Stunden pro Tag aus. Das ist praktisch bei reduzierten Stundensätzen bei Teilzeitarbeit.

**Comment by KlausRicharz** [comment]
Macht er das nicht bereits? Wenn ich den Urlaubsauftrag auswähle, belegt er die Buchungszeit so gut vor, wie ihm das möglich ist. Durch die 5 Minuten-Begrenzung ist das nicht bei allen exakt, da wir bei HBT immer von einer 5-Tage-Woche bei der Wochenarbeitszeit und beim Urlaubsanspruch, Krankheit etc. ausgehen.

**Comment by KlausRicharz** [comment]
Ich sehe nun eine Möglichkeit, Zeiten minutengenau buchen zu können. Nicht, dass man das für normale Buchungen benötigt, aber für Urlaube ist das hilfreich.

**Comment by KlausRicharz** [comment]
Durch die neue Funktion "minutengenau" sollte das jetzt gehen.
