### ISSUE TITLE
Projektwechsel bei Buchung in Einzelübersicht in Firefox nicht möglich

### ISSUE THREAD

**Issue by ruben-ms** [HBTGmbH/salat#125]
Ist:
1. Menü Buchungen, Einzelübersicht, Neue Buchung
2. Auftrag und Unterauftrag sind (wegen Sternchen-/Default-Verwendung vorbelegt)
3. Manueller Wechsel des Auftrags über Select-Box ist nicht möglich. Ich kann nicht vom Aufrag 1495 zu HBT-Zeit wechseln. Der Wert wird nach Sekundenbruchteilen wieder auf den Default-Auftrag zurückgesetzt.

Soll: Projektwechsel soll trotz Default-Auftrag möglich sein.

Workaround: 
Sternchen für Default-Auftrag entfernen. Danach lässt sich das Projekt wechseln.

**Comment by KlausRicharz** [comment]
Funktioniert im Chrome, in Firefox anscheinend nicht (Info von Ruben)
