### ISSUE TITLE
Alle Buchungen eines Projektes für Projektverantwortlichen sichtbar machen

### ISSUE THREAD

**Issue by hehu80** [HBTGmbH/salat#152]
Früher™ konnten alle User alle Buchungen sehen.
Seit einem der letzten Releases können das nur noch Manager bzw. Personalverantwortliche.

Für jemand der keine Personalverantwortung hat, aber dennoch ein bestimmtes Projekt "im Blick" haben muss, wäre es praktisch einen Überblick über alle gebuchten Stunden eines bestimmten Projektes zu haben.

**Comment by KlausRicharz** [comment]
Wir im Rahmen von #167 erledigt
