### ISSUE TITLE
Self-service Passwort zusenden per Mail

### ISSUE THREAD

**Issue by BelloWaff** [HBTGmbH/salat#156]
Im Fall eines vergessenen Passwortes ist es wünschenswert, wenn der User sich das autonom per Mail anfordern kann, so wie bei den allermeisten anderen Services auch. Spart nicht nur der Infrastruktur Arbeit, ist auch für den User angenehmer und für diesen im Zweifel auch jederzeit durchführbar, da Adminuser auch mal nicht verfügbar sein können.

**Comment by KlausRicharz** [comment]
Der Email Versand muss erst wieder aktiviert werden.

**Comment by youseeus** [comment]
dies sollte ja beim Umzug auf azure-Auth obsolet sein
