### ISSUE TITLE
Default-Unterauftrag nicht wirksam nach Tageswechsel

### ISSUE THREAD

**Issue by claa5** [HBTGmbH/salat#183]
Folgender kleiner Bug hat bei mir gerade öfter zu falschen Buchungen geführt:
Wenn ich auf "Neue Buchung" gehe, dann ist der per Sternchen favorisierte Default-Auftrag und - Unterauftrag selektiert. Wenn ich dann über die blauen Pfeile den Tag ändere, springt der Unterauftrag auf den ersten in der Liste zurück. Nach Tageswechsel funktioniert also der Default-Auftrag weiterhin, aber nicht der Default-Unterauftrag.

**Comment by KlausRicharz** [comment]
Konnte das Problem lokal nachstellen.
