### ISSUE TITLE
Layout Datepicker verbessern

### ISSUE THREAD

**Issue by claa5** [HBTGmbH/salat#186]
Der Datepicker ist uralt und basiert noch auf einem Design, dass ich irgendwann vor 20 Jahren mal bei Geofox eingebaut hatte...
Es wäre schön, wenn da eine modernere Komponente oder zumindest ein besseres Layout verwendet werden könnte.
Kritikpunkte am aktuellen Datepicker:
* Öffnet sich als eigenes Fenster mit überflüssigen Schaltflächen, manchmal auch auf dem falschen Bildschirm
* Oben steht immer "about:blank" !?
* Layout ist total gequetscht mit sehr kleinen, schwer zu treffenden Schaltflächen

**Comment by KlausRicharz** [comment]
DatePicker fehlt noch in Buchungsmaske.
