### ISSUE TITLE
Datenschutz

### ISSUE THREAD

**Issue by Kryptikk92** [HBTGmbH/salat#2]
Ich möchte, dass nicht berechtigte Kollegen (also alle außer GF, Teamleiter, Projektleiter) keinen Zugriff auf meine Buchungen haben

**Comment by ljhbt** [comment]
Das bin übrigens ich, ich war nur mit dem falschen account angemeldet.

**Comment by KlausRicharz** [comment]
Bitte um Test unter https://test-salat.hbt.de/
