### ISSUE TITLE
Datenbank als Container (test und prod) 

### ISSUE THREAD

**Issue by twupp** [HBTGmbH/salat#211]
Aus Sicht der Infrastruktur und als Vorbereitung für einen Betrieb in der Cloud wäre es gut, die Datenbank(en) in einen Container zu migrieren, der zusammen mit dem Salat-Container betrieben wird.
In Kürze läuft eine Linux-VM nur noch für die Salat-Datenbanken, diese würden wir gerne abstellen.

**Comment by youseeus** [comment]
wie wäre es komplett auf DB-as-a-Service umzustellen? ohne Umwege?

**Comment by twupp** [comment]
Ja klar, dabei müssen wir das Thema Datenschutz gerade beim Salat natürlich besonders beachten. Bis dahin, dass die Daten wirklich nur von Berechtigten gesehen werden dürfen (wer ist das?).
Möglichst beim gleichen Anbieter, wo später auch der Salat läuft, da bin ich mir aber noch nicht sicher. Vorschläge?
