### ISSUE TITLE
Datepicker springt auf falsches Datum

### ISSUE THREAD

**Issue by BelloWaff** [HBTGmbH/salat#219]
Unter bestimmten Umständen springt der Datepicker auf einen falschen Tag, was bei der Eingabe sehr 

Salat-Fehler bei Datumsauswahl:
Heutigen Tag (mittlerer Auswahlbutton) auswählen-->Matrixansicht-->einen anderen Tag auswählen-->Salatbuchung (etwa die Stunden) anpassen und speichern-->Tag springt auf den heutigen Tag, angezeigt werden jedoch die Buchungen des eigentlich ausgewählten Tags.

Das ist sehr nervig, weil es so oft passiert, dass Buchungen auf dem falschen Tag landen und man es mit Pech nicht merkt.

**Comment by BelloWaff** [comment]
Ich finde diesen Bug ziemlich wichtig. Ich habe mal wieder auf ein falsches Datum gebucht und das erst nach einer Weile gemerkt, weil das Datum umgesprungen ist.

**Comment by BelloWaff** [comment]
Jetzt springt er auf das "Datum" dd.mm.yyyy ... marginal besser ;-) Interessanterweise merkt er sich das Datum trotzdem irgendwo, wenn ich den Pfeil links oder rechts springe, kommt das falsche Datum wieder

**Comment by KlausRicharz** [comment]
Wo hast du den Test gemacht?
