### ISSUE TITLE
JWT als Authentifizierung

### ISSUE THREAD

**Issue by youseeus** [HBTGmbH/salat#240]
Azure authproxy macht eine eigene Authentifizierung unnötig. für die Autorisierung brauchen wir eine Spring-eigene JWT-Implementierung.
AK:
- Salat Zugang wird automatisch per JWT abgesichert.
- alte Authentifizierung wurde ausgebaut
- Zugang für Programme ist möglich ähnlich zu den bisherigen Tokens (sollte user-basiert sein)

**Comment by youseeus** [comment]
Todo: 
- key-vault benutzen
- die redirect url 'http://localhost:8080/login/oauth2/code/' in den salat-test app einzutragen:
https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/Authentication/appId/865b95c4-f360-4ca2-ba20-4fe28e3ea4f6/isMSAApp~/false

**Comment by hehu80** [comment]
Wie wird der Zugang für Programme (Rest API) möglich gemacht?

**Comment by youseeus** [comment]
TODO for die Produktiv Schaltung:

- Environment-Varibalen übertragen
  - AZURE_AD_*
  - SPRING_PROFILES_ACTIVE
- in der Tabelle employee im feld Feld 'sign' @hbt.de hinzufügen

**Comment by KlausRicharz** [comment]
Wurde im Rahmen des Tickets #301 erledigt
