### ISSUE TITLE
Datums Blätter Buttons springen

### ISSUE THREAD

**Issue by florian-hbt** [HBTGmbH/salat#282]
Da das Dropdown für die Monatsauswahl auf z.B. der Matrixübersichtsseite keine feste Breite hat springen die Buttons rechts davon. Wenn man mal durch die Liste der Blättern möchte passiert es gerne, dass man ohne Bewegung der Maus auf einmal ein anderer Button (z.B. zu aktuellem Datum springen) und dem Cursoner hat. Wenn das Dropdown für die Moanate (Jahre bleiben wohl erstmal noch 4 stellig) eine feste breite hätte würde das nicht passieren.

**Comment by KlausRicharz** [comment]
Passiert mir auch manchmal.
