### ISSUE TITLE
Bilder/Farben aktualisieren

### ISSUE THREAD

**Issue by skies5** [HBTGmbH/salat#3]
Das Hintergrundbild zeigt noch das alte HBT-Logo (den "Poller"), das 2019(?) durch das Schriftlogo ersetzt wurde.

Die Farben passen nicht mehr zu unserem aktuellen CI. Die korrekten Farbwerte stehen im Wiki unter https://hbteam.atlassian.net/wiki/spaces/VERTRIEB/pages/524890/CI+-+Corporate+Identity

Es gibt ein aktuelleres Salat/Batavia-Logo, das im Rahmen des Hackathon 2019 genutzt wurde und zB hier zu sehen ist: https://hbteam.atlassian.net/wiki/spaces/INTRA/pages/459769/Architektur+More

TODO:
- Hintergrundbild austauschen
- css-Farbschema aktualisieren
- Salat-Logo auf Login-Seite aktualisieren
- favicon aktualisieren

Nice to Have:
- Design modernisieren (wahrscheinlich besser als eigenes Ticket)

**Comment by franzxschmid** [comment]
Nicht den Poller 😢
