### ISSUE TITLE
Freigabeübersicht: letzten des Monats auswählen

### ISSUE THREAD

**Issue by anoHBT** [HBTGmbH/salat#339]
Wenn man in der Freigabeübersicht Februar auswählt, wird der 31.02.2024 ausgewählt. Der Dialog zeigt den 29.02.2024 als ausgewählt an. Bei einer versuchten Freigabe im Zustand auf dem Screenshot kommt es zu einer Weiterleitung auf eine WhiteErrorPage. Richtiger wäre immer den letzten Tag des Monats freizugeben bzw auszuwählen
![Clipboard - 29  Februar 2024 14_58](https://github.com/HBTGmbH/salat/assets/53003622/b1950a46-e443-437a-94c4-aacc771a75d2)

**Comment by lixput** [comment]
+1, ich habe gerade mehrmals vergeblich versucht den April freizugeben, bis ich den Fehler überhaupt gesehen habe.

**Comment by lixput** [comment]
Bin dem gerade nochmal ein bisschen nachgegangen und es scheint ein allgemeiner Bug in dem Datepicker zu sein. Ich habe es auch in den anderen Datumsauswahlen reproduzieren können, z.B. https://salat.hbt.de/do/CreateDailyReport. Er tritt immer dann auf, wenn ich 

1. ein Datum in Monat _a_ mit einem Tag _x_ auswähle, das in Monat _b_ nicht vorhanden ist
2. dann direkt über die Monatsauswahl (nicht über die Pfeile) zu Monat _b_ springe

Resultat ist, dass das (nicht existente) Datum x.b. ausgewählt ist, anstatt [letzter Tag im Monat b].b.
Korrigieren kann ich es offenbar nur, wenn ich den Datepicker nach der Auswahl erneut öffne (oder ich hab es nicht gecheckt).

Zu erwägen wäre, ob man an der Stelle überhaupt einen Datepicker braucht oder ob ein Dropdown der Monate und Jahre nicht besser ist. (Geben Leute Buchungen zu irgendwelchen anderen Tagen als dem Monatsletzten frei?)

**Comment by anoHBT** [comment]
Ich glaube auch, dass ein Monatspicker ausreichen sollte und der Salat kann dann im Backend den letzten Monatstag berechnen.

**Comment by KlausRicharz** [comment]
Es gibt die Anforderung auch innerhalb eines Monats die Stunden freigeben zu können.

**Comment by lixput** [comment]
Ich habe die von mir oben beschriebenen Schritte nochmal ausgeführt. Auf https://salat.hbt.de/do/CreateDailyReport kommt jetzt eine Fehlermeldung beim Versuch den 31.06.2024 auszuwählen.
![image](https://github.com/user-attachments/assets/0eacbab3-c047-48f5-b52b-33dc5dba83c7)
Das reicht ja völlig. Eigentlich müsste man die nur bei der Freigabe ebenfalls anzeigen und das Problem hätte sich schon gelöst.
