### ISSUE TITLE
viertelstundengenau buchen

### ISSUE THREAD

**Issue by youseeus** [HBTGmbH/salat#349]
Häufig reichen dem Kunden virtelstundengenaue Buchungen. also sollte es möglich sein bei Buchungen 0, 15, 30, 45 Minuten auszuwähelen

**Comment by twupp** [comment]
Nutzen: Man braucht nicht zu scrollen beim Buchen. Evtl. kann man die 5-Minuten-Schritte einfach weg lassen und neben der sowieso möglichen minunten-genauen Buchung nur 15-Minuten-Schritte anbieten.

**Comment by KlausRicharz** [comment]
Ich kann mir als Alternative vorstellen, dass wir die Reihenfolge erstmal ändern. Also 0,15,30,45,5,10,20,25,35,40,50,55
Ich mache mal eine Auswertung, wie oft abseits der 15 Minuten gebucht wird.

**Comment by KlausRicharz** [comment]
2-3% der Buchungen sind nicht viertelstundengenau
