### ISSUE TITLE
Rechtekonzept: Fortbildung

### ISSUE THREAD

**Issue by florian-hbt** [HBTGmbH/salat#351]
**User Story:**
Als Fortbildungsbeauftrager würde ich gerne die Fortbildungsrelevanten Buchung der Mitarbeiter sehen können, um mir entweder im Einzelfall anschauen was ein Mitarbeiter gemacht hat (z.B. als Vorbereitung für eine Beratung) oder aber um mir einen Überblick zu verschaffen was und wieviel Fortbildung Firmenweit gemacht wurde.

**Comment by KlausRicharz** [comment]
Reicht dir hierfür ein Report, Parameter wären der Mitarbeiter und das Jahr?

**Comment by KlausRicharz** [comment]
Report "HBT: Fortbildungen" erstellt und fp und cg zugeordent.
