### ISSUE TITLE
Fehlenden Arbeitsbeginn/Pausendauer in Matrixübersicht kennzeichnen

### ISSUE THREAD

**Issue by cghbt** [HBTGmbH/salat#359]
Da wir ja jetzt immer den Arbeitsbeginn und die Pausendauer buchen müssen, wäre es gut, wenn der Salat anzeigen würde, ob das für alle Tage vorhanden ist.
Man könnte bspw. in der Matrixübersicht kennzeichnen, wenn es Tage mit Buchungen aber ohne diese Angaben gibt. Diese Tage könnte man mit einem entsprechenden Icon oder farbig kennzeichnen.

Aktuell kann man das nur etwas mühsam über die Einzelübersicht prüfen, indem man den ganzen Monat Tag für Tag durchklickt.

**Comment by hehu80** [comment]
Was hältst du vom Anzeigen der Anfangs-/Pausenzeiten als ersten Wurf?
![image](https://github.com/HBTGmbH/salat/assets/1446270/adba6b49-9ea4-4213-b9d0-e924118c6582)

**Comment by cghbt** [comment]
Ja, sieht schon ganz gut aus!
Man könnte das vielleicht noch Farblich oder mit Symbolen kennzeichnen, so wie Adrian auch vorgeschlagen hat. Also vielleicht, Spalten mit Buchungen aber ohne Arbeitsbeginn/Pausendauer rot einfärben. Oder da in die unteren Zeilen rote "X"-Icons reinmachen.

**Comment by hehu80** [comment]
Ein passendes Symbol hab ich gerade nicht. Wie ist das?
![image](https://github.com/HBTGmbH/salat/assets/1446270/e8aecc19-2262-4225-b0ae-e224632446a6)

**Comment by cghbt** [comment]
Ja, gut. Nur das Rot ist sehr Primärfarbe, das tut etwas in den Augen weh.
Ich würde ein etwas sanfteren Farbton nehmen, so in diese Richtung:
https://imagecolorpicker.com/color-code/e05b50
 
VG Claas

**Comment by hehu80** [comment]
Eine Farbe, die Mandy heißt, nehme ich natürlich sofort :smile: 
![image](https://github.com/HBTGmbH/salat/assets/1446270/73f24036-1b97-4439-b17f-ec23f04449a5)

**Comment by hehu80** [comment]
Die Prüfung, ob die Länge der Pause korrekt ist, habe ich bewusst ausgeklammert, weil @Peglow-C damit schon angefangen hatte (https://github.com/HBTGmbH/salat/issues/354).
Seine Änderungen könnte man jetzt bestimmt auch in der Matrixübersicht nutzen.
Gibt auch schon ein neues Issue dazu: https://github.com/HBTGmbH/salat/issues/368
