### ISSUE TITLE
Überstunden für diesen Monat nicht korrekt durch Überstundenausgleich

### ISSUE THREAD

**Issue by janausis** [HBTGmbH/salat#432]
Als Werkstudent hat man ja einige Tage an denen man nicht arbeitet, wodurch man viel mit Überstundenausgleich buchen muss. Nun ist aber die Anzeige für aktuelle Überstunden in diesem Monat sehr verwirrend gestaltet. Ich habe laut dieser Anzeige z.B. aktuell 19 Überstunden, was gar nicht möglich ist, weil mir sogar noch Stunden für diesen Monat fehlen. Dadurch ist es leider sehr unübersichtlich, wie viel ich diesen Monat noch arbeiten muss. In der Überstundenübersicht ergibt die Zahl deutlich mehr Sinn.

**Comment by KlausRicharz** [comment]
Ist das noch aktuell?

**Comment by janausis** [comment]
Ja, zu Anfang des Monats fällt es nicht so sehr auf, aber Ende Oktober hatte ich mehr als 20 Überstunden laut der Anzeige an beschriebener Stelle

**Comment by KlausRicharz** [comment]
Hast du ein Beispiel? Wenn ich mir die Matrix anschaue, sehe ich das nicht.

**Comment by janausis** [comment]
Ich habe letzten Monat auf die Minute genau meine Soll-Stunden erfüllt, trotzdem ist meine Differenz mit Überstundenausgleich bei 28 stunden, weil ich z.B. nur Montag und Dienstag arbeite und die restlichen Tage als Überstunden buchen muss, weil ich ja nicht gearbeitet habe. Die Überstundenübersicht zeigt mir korrekt 0 Überstunden für Oktober an.

![image](https://github.com/user-attachments/assets/0741fcf9-ec1d-4fcc-bb95-d1966fb0d1b1)

**Comment by KlausRicharz** [comment]
ich konnte es nachvollziehen
