### ISSUE TITLE
CSV Export und Import von Zeitbuchungen

### ISSUE THREAD

**Issue by hehu80** [HBTGmbH/salat#439]
Als CSV Datei könnten Zeitbuchungen einfach in Drittprogrammen bearbeitet werden. Eine Export- und Import-Funktion der Zeitbuchungen als CSV-Datei würde das Erstellen und Bearbeiten von Zeitbuchungen, insb. wenn man jeden Tag viele einzelne Buchungen durchführen muss, vereinfachen.

**Comment by KlausRicharz** [comment]
Es fehlt noch eine schlaue Behandlung von Workingday

**Comment by hehu80** [comment]
Ja, die Workingdays fehlen noch. Mache ich ein neues Issue für auf.
