### ISSUE TITLE
Matrixübersicht berechnet keine Überstunden und Urlaubstage in neuem Monat ohne gespeicherten Arbeitsbeginn

### ISSUE THREAD

**Issue by Marian-Begemann-HBT** [HBTGmbH/salat#456]
Die Matrixübersicht zeigt im unteren Abschnitt "Überstunden und Urlaubstage" keine Werte für "Buchungen freigeben bis/Überstunden/Urlaub(IST/SOLL)" an.

Rahmenbedingungen:
- Neuer Monat
- Bisher keine Buchung (außer Urlaubstage später im Monat)

Die Berechnung funktioniert, sobald ein Arbeitsbeginn gespeichert wird.

**Comment by KlausRicharz** [comment]
Kann ich nicht nachvollziehen, weder im Live- noch im Testsystem. Brauche Hilfe :-)

**Comment by KlausRicharz** [comment]
Bitte erneut melden, falls es wieder auftritt.
