### ISSUE TITLE
doppelte Auflistung von Minuten beim buchen in Dropdown

### ISSUE THREAD

**Issue by anoHBT** [HBTGmbH/salat#59]
![grafik](https://user-images.githubusercontent.com/53003622/156565283-95497272-65e4-4b7f-988a-092fd0ea6ef6.png)

Im Dropdown für die Minuten bei der Buchung sind die Viertelstunden-Minuten-Sätze doppelt.
Entweder entfernt man diese um Verwirrung zu vermeiden oder führt einen Strich zwischen 45 und dem zweiten 00 ein.

**Comment by KlausRicharz** [comment]
Ich habe das Thema komplett anders gestaltet. Entweder man kann in 5er Schritten buchen, oder minutengenau. Hat man einen Vertrag mit einer Tagesarbeitszeit, die nicht zu den 5er Schritten passt, z.B. 6:42, dann schaltet der Salat automatisch nach Auswahl des Auftrags (z.B. Urlaub) auf minutengenau.
