### ISSUE TITLE
Bug: Einzelübersicht: "Neue Buchung" aktualisiert Arbeitszeit nicht

### ISSUE THREAD

**Issue by skies5** [HBTGmbH/salat#74]
Beobachtet auf https://test-salat.hbt.de.

Bug in der Einzelübersicht eines neuen Tages:
Beim Anlegen von Buchungen per Klick auf "Neue Buchung" werden "IST-Arbeitsende" und "gesamt"-Felder nicht aktualisiert und bleiben leer. Dies passiert auch beim wiederholten Anlegen von Buchungen.

Die Felder werden erst befüllt, wenn man neben einer bestehenden Buchung auf den "Speichern"-Button (Disketten-Icon) klickt, egal ob tatsächlich etwas geändert wurde.

![Screenshot 2022-03-17 172903](https://user-images.githubusercontent.com/49303555/158848371-b1c07349-d0ea-43b6-b935-435895989c14.png)
![Screenshot 2022-03-17 173001](https://user-images.githubusercontent.com/49303555/158848190-f9e6f4be-c293-4a71-9887-b38fa526de5f.png)

**Comment by KlausRicharz** [comment]
Bitte auf Testsystem prüfen.

**Comment by skies5** [comment]
Ist gefixt. Supi!
