### ISSUE TITLE
Teamleiter können Stunden anderer Mitarbeiter nicht ändern

### ISSUE THREAD

**Issue by ruben-ms** [HBTGmbH/salat#75]
Als Team- bzw. Bereichsleiter kann ich Stunden anderer Mitarbeiter ändern, wenn dieser die Stunden freigegeben hat. Warum geht das nicht, wenn diese noch nicht freigegeben sind?
Bitte die nicht freigegebenen Stunden änderbar machen. (Neue Buchungen kann ich ja auch für andere Mitarbeiter erstellen.)

**Comment by KlausRicharz** [comment]
Neue Buchungen für andere Mitarbeiter kannst du nur in Zeiträumen erstellen, die freigegeben sind. Oder?

**Comment by KlausRicharz** [comment]
Im aktuellen Test-System ist dies zumindest so.

**Comment by KlausRicharz** [comment]
Erklärung: solange ein Mitarbeiter seine Stunden nicht freigegeben hat, kann niemand anderes seine Stunden anpassen. Diese sind also in seiner Hoheit. Gibt er diese frei, sind sie nun in der Hoheit des Managements. Nimmt das Management dieses Ab, können nur noch Admins Änderungen vornehmen.

Dies wurde explizit so gefordert, damit keine Verwirrung entsteht.

Hinweis: Freigaben oder Abnahmen werden immer durch Angabe eines Enddatums (bis wann einschl.) vorgenommen. Alle Buchungen bis zu diesem Datum (einschl.) gelten dann als freigegeben bzw. abgenommen.

**Comment by ruben-ms** [comment]
Gut, wenn das die Anforderung war/ist, können wir das Ticket auch schließen.
