### ISSUE TITLE
Bug: Einzelübersicht zeigt nach neuer Buchung minutengenaue Einträge falsch an.

### ISSUE THREAD

**Issue by skies5** [HBTGmbH/salat#78]
Getestet auf https://test-salat.hbt.de.

How to reproduce:
- Einzelübersicht öffnen (https://test-salat.hbt.de/do/ShowDailyReport)
- "Neue Buchung" anlegen, minutengenaue Zeit eintragen (zB 1h18min)
-- Buchung wird korrekt angezeigt
- "Neue Buchung" anlegen, reguläre Zeit (zB 1h)
-- Einzelübersicht zeigt nun für die erste Buchung unvollständige Zeit an (Minutenfeld steht auf "00").

![grafik](https://user-images.githubusercontent.com/49303555/159651514-7437cf83-7838-4d30-b10d-1097b4ec53ae.png)

Anmerkungen dazu:
- Die Checkbox "minutengenau" in der Übersicht ist einfach aus, nachdem man eine "reguläre" Buchung angelegt hat. Diese Checkbox sollte immer an sein, wenn eine minutengenaue Buchung für den Tag existiert.
- Das Minutenfeld in minutengenaue Buchungen sollte nicht auf "0" runtergerundet werden, wenn die Anzeige nicht minutengenau ist, sondern auf die nächste 15min-Einheit.
- minutengenaue Buchungen müssen irgendwie erkennbar sein, wenn die Ansicht nicht minutengenau ist. Sonst erkennt man nicht, in welcher Buchung sich in Wirklichkeit mehr Zeit verbirgt, als gerade sichtbar ist.

**Comment by KlausRicharz** [comment]
Das geht besser :-)

**Comment by skies5** [comment]
Ticket nochmal aktualisiert.
