### ISSUE TITLE
Matrixübersicht: Monatswechsel mit vor und zurück Button 

### ISSUE THREAD

**Issue by TimZielasko** [HBTGmbH/salat#9]
Ich würde es begrüßen, wenn es zwei Buttons geben würde auf der Matrixübersicht.
Die folgende Funktion haben: einen Monat vor und einen Monat zurück. 
Den z.B. beim Jahres Wechsel ist es immer wieder nervig vom Januar auf den Dezember im vor Jahr zu wechseln

**Comment by KlausRicharz** [comment]
Funktion hinzugefügt
