### ISSUE TITLE
Neue Buchung - Auftrag / Unterauftrag Favoriten Problem

### ISSUE THREAD

**Issue by TimZielasko** [HBTGmbH/salat#90]
Wenn man Favoriten gesetzt hat, kann man keinen anderen Auftrag/Unterauftrag auswählen zum buchen

**Comment by youseeus** [comment]
ich kann andere auswählen, aber das wird ignoriert
erst beim bearbeiten, wird das geändert

**Comment by youseeus** [comment]
ich nehme es zurück, bei mir geht es auch nicht

**Comment by sjthiessen** [comment]
Die Lokalen Website-Daten löschen hilft, um die Favoriten wieder zu entfernen
