### ISSUE TITLE
Buchung rutscht nach Änderung an den Beginn der Liste

### ISSUE THREAD

**Issue by skurzbac** [HBTGmbH/salat#94]
Nach einer Änderung einer bestehenden Buchung (z.B. Dauer) verändert sich die Sortierung der Liste. Nach dem erneuten Laden sind die Buchungen wieder an der alten Position. Siehe https://salat.hbt.de/do/UpdateDailyReport?trId=332453

**Comment by KlausRicharz** [comment]
In welcher Ansicht rutscht die Buchung nach oben?

**Comment by KlausRicharz** [comment]
Bei mir habe ich das nicht feststellen können. Wir können das auf dem Testsystem mal versuchen.
