### ISSUE TITLE
Matrixübersicht, Einzelübersicht usw werden nicht angezeigt

### ISSUE THREAD

**Issue by rsttec** [HBTGmbH/salat#95]
Gleiches ist bei mehreren anderen Menüpunkten

Grund vermutlich: Bei allen Dropdownlisten wo der Mitarbeiter ausgewählt werden, kann steht  "No result found"

Bei der Einzelübersicht kommt die Fehlermeldung
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri May 13 09:34:13 CEST 2022
There was an unexpected error (type=Internal Server Error, status=500).

**Comment by KlausRicharz** [comment]
Bitte erneut testen. War ein Datenproblem.
