### ISSUE TITLE
"Gesamtbudget reicht nicht aus"

### ISSUE THREAD

**Issue by Timmster** [HBTGmbH/salat#97]
Ich kann nicht mehr auf "1488 - Entwicklung ts" buchen. 
Hiweis: "Gesamtbudget reicht nicht aus"
An wen muss ich mich wenden?

**Comment by KlausRicharz** [comment]
Im Salat war ein Budget für den Auftrag, für den Unterauftrag und für deinen Mitarbeiterauftrag hinterlegt. Das wird jetzt berücksichtigt. Habe das Budget entfernt.

**Comment by Timmster** [comment]
thx
